// Builds the extension into dist/:
//   dist/CSXS/manifest.xml
//   dist/panel/{index.html, panel.css, panel.js, maplibre-worker.js, encode-worker.js, maplibre-gl.css}
//   dist/host/lazymaplayers.jsx   (src/host/*.jsx concatenated in name order)
//   dist/data/{natural-earth.pmtiles, borders.geojson, labels.json, admin1-index.json, admin1/*.json}
//   dist/LICENSE
//
//   node tools/build.mjs [--dev] [--minify] [--out <folder>]
//
// --dev --minify is a development build (debug port, test automation) with the release's minified
// code, for running the in-AE tests against what users get.
// --out builds somewhere else than dist/ (the release script stages there, so a running After Effects
// that uses the dist/ link is never touched).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";
import { toAsciiEscapes } from "./ascii.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outIndex = process.argv.indexOf("--out");
const dist = outIndex > 0 ? path.resolve(process.argv[outIndex + 1]) : path.join(root, "dist");
const dev = process.argv.includes("--dev");
const minify = !dev || process.argv.includes("--minify");
const target = ["chrome99"];

const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

function buildHost() {
  const dir = path.join(root, "src", "host");
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".jsx")).sort();
  const header = `// LazyMapLayers ${pkg.version} host script. Generated by tools/build.mjs; edit src/host instead.\n`;
  const body = files.map((f) => `// ---- ${f} ----\n${fs.readFileSync(path.join(dir, f), "utf8").replace(/^﻿/, "")}`).join("\n");
  const out = path.join(dist, "host", "lazymaplayers.jsx");
  fs.mkdirSync(path.dirname(out), { recursive: true });
  const text = header + body.replace(/LML\.version = "[^"]*";/, `LML.version = "${pkg.version}";`);
  fs.writeFileSync(out, toAsciiEscapes(text), "utf8");
  return files.length;
}

async function main() {
  const started = Date.now();
  fs.rmSync(dist, { recursive: true, force: true });

  const manifest = fs
    .readFileSync(path.join(root, "CSXS", "manifest.xml"), "utf8")
    .replace(/ExtensionBundleVersion="[^"]*"/, `ExtensionBundleVersion="${pkg.version}"`)
    .replace(/(<Extension Id="com\.sohan\.LazyMapLayers\.panel" Version=")[^"]*"/, `$1${pkg.version}"`);
  fs.mkdirSync(path.join(dist, "CSXS"), { recursive: true });
  fs.writeFileSync(path.join(dist, "CSXS", "manifest.xml"), manifest, "utf8");
  if (dev) fs.writeFileSync(path.join(dist, ".debug"), debugFile(), "utf8");

  copy(path.join(root, "LICENSE"), path.join(dist, "LICENSE"));
  copy(path.join(root, "panel", "index.html"), path.join(dist, "panel", "index.html"));
  copy(path.join(root, "panel", "panel.css"), path.join(dist, "panel", "panel.css"));
  copy(path.join(root, "node_modules", "maplibre-gl", "dist", "maplibre-gl.css"), path.join(dist, "panel", "maplibre-gl.css"));

  await esbuild.build({
    entryPoints: [path.join(root, "node_modules", "maplibre-gl", "dist", "maplibre-gl-worker.mjs")],
    outfile: path.join(dist, "panel", "maplibre-worker.js"),
    bundle: true,
    format: "esm",
    target,
    minify,
    legalComments: "inline",
    logLevel: "warning"
  });

  await esbuild.build({
    entryPoints: [path.join(root, "src", "panel", "render", "encodeWorker.ts")],
    outfile: path.join(dist, "panel", "encode-worker.js"),
    bundle: true,
    format: "iife",
    platform: "browser",
    target,
    minify,
    legalComments: "inline",
    logLevel: "warning"
  });

  await esbuild.build({
    entryPoints: [path.join(root, "src", "panel", "main.tsx")],
    outfile: path.join(dist, "panel", "panel.js"),
    bundle: true,
    format: "iife",
    platform: "browser",
    target,
    jsx: "automatic",
    jsxImportSource: "preact",
    sourcemap: dev && !minify ? "inline" : false,
    minify,
    legalComments: "inline",
    define: { "process.env.NODE_ENV": dev ? '"development"' : '"production"' },
    logLevel: "warning"
  });

  const hostFiles = buildHost();

  const archive = path.join(root, "data", "generated", "natural-earth.pmtiles");
  if (fs.existsSync(archive)) copy(archive, path.join(dist, "data", "natural-earth.pmtiles"));
  else console.warn("warning: data/generated/natural-earth.pmtiles missing; run node tools/prepare-natural-earth.ts");
  for (const overlay of ["borders.geojson", "labels.json"]) {
    const file = path.join(root, "data", "generated", overlay);
    if (fs.existsSync(file)) copy(file, path.join(dist, "data", overlay));
    else console.warn(`warning: data/generated/${overlay} missing; run node tools/prepare-world-overlays.ts`);
  }
  // Provinces: an index for search and one file of polygons per country, read on demand.
  const provinces = path.join(root, "data", "generated", "admin1");
  const provinceIndex = path.join(root, "data", "generated", "admin1-index.json");
  if (fs.existsSync(provinceIndex) && fs.existsSync(provinces)) {
    copy(provinceIndex, path.join(dist, "data", "admin1-index.json"));
    for (const name of fs.readdirSync(provinces)) copy(path.join(provinces, name), path.join(dist, "data", "admin1", name));
  } else console.warn("warning: data/generated/admin1 missing; run node tools/prepare-admin1.ts");

  const size = (f) => (fs.statSync(path.join(dist, f)).size / 1024).toFixed(0) + " KB";
  console.log(
    `built ${pkg.version}${dev ? " (dev)" : ""} in ${((Date.now() - started) / 1000).toFixed(1)} s: ` +
      `panel.js ${size("panel/panel.js")}, maplibre-worker.js ${size("panel/maplibre-worker.js")}, host ${hostFiles} files`
  );
}

function debugFile() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<ExtensionList>
    <Extension Id="com.sohan.LazyMapLayers.panel">
        <HostList>
            <Host Name="AEFT" Port="8123" />
        </HostList>
    </Extension>
</ExtensionList>
`;
}

await main();
